export const salesDefaults = {
    nome: "",
    cpf: "",
    nascimento: "",
    rg: "",
    emissorRg: "",
    email: "",
    emailConfirmacao: "",
    celular: "",
    telefone: "",
    cep: "",
    numero: "",
    rua: "",
    bairro: "",
    cidade: "",
    complemento: "",
    referencia: "",
    tipoMoradia: "casa",
    aceitouPrivacidade: false,
    planoId: "",
    dataInstalacao: "",
    periodoInstalacao: "manha",
    vencimentoDia: 2,
    formaPagamento: "debito_avista",

    responsaveis: [],
};
