import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-multi-carousel/lib/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { IBM_Plex_Sans } from 'next/font/google'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ibmPlex = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400','700','500']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${ibmPlex.className}`}
      >
        {children}
      </body>
    </html>
  );
}
